Slurm job started at 18/06/2023_19:44:05

NNODES = 4
SIMUNODES = 2
WORKERNODES = 2
NPROC = 4
NWORKER = 60
..['tcp://10.7.0.132:33265', 'tcp://10.7.0.132:33795', 'tcp://10.7.0.132:34401', 'tcp://10.7.0.132:35112', 'tcp://10.7.0.132:35136', 'tcp://10.7.0.132:35223', 'tcp://10.7.0.132:35281', 'tcp://10.7.0.132:35764', 'tcp://10.7.0.132:36068', 'tcp://10.7.0.132:36327', 'tcp://10.7.0.132:36670', 'tcp://10.7.0.132:36692', 'tcp://10.7.0.132:39096', 'tcp://10.7.0.132:39677', 'tcp://10.7.0.132:39769', 'tcp://10.7.0.132:39781', 'tcp://10.7.0.132:40319', 'tcp://10.7.0.132:40659', 'tcp://10.7.0.132:41363', 'tcp://10.7.0.132:42855', 'tcp://10.7.0.132:43057', 'tcp://10.7.0.132:43821', 'tcp://10.7.0.132:43961', 'tcp://10.7.0.132:44064', 'tcp://10.7.0.132:44351', 'tcp://10.7.0.132:44427', 'tcp://10.7.0.132:44648', 'tcp://10.7.0.132:45228', 'tcp://10.7.0.132:46049', 'tcp://10.7.0.132:46521', 'tcp://10.7.0.133:33668', 'tcp://10.7.0.133:33922', 'tcp://10.7.0.133:35386', 'tcp://10.7.0.133:35392', 'tcp://10.7.0.133:35533', 'tcp://10.7.0.133:35542', 'tcp://10.7.0.133:35755', 'tcp://10.7.0.133:36300', 'tcp://10.7.0.133:37775', 'tcp://10.7.0.133:38093', 'tcp://10.7.0.133:38397', 'tcp://10.7.0.133:38437', 'tcp://10.7.0.133:38536', 'tcp://10.7.0.133:38833', 'tcp://10.7.0.133:39158', 'tcp://10.7.0.133:39221', 'tcp://10.7.0.133:39514', 'tcp://10.7.0.133:39720', 'tcp://10.7.0.133:39797', 'tcp://10.7.0.133:39823', 'tcp://10.7.0.133:40576', 'tcp://10.7.0.133:40759', 'tcp://10.7.0.133:41175', 'tcp://10.7.0.133:43312', 'tcp://10.7.0.133:44092', 'tcp://10.7.0.133:44232', 'tcp://10.7.0.133:44606', 'tcp://10.7.0.133:44936', 'tcp://10.7.0.133:45922', 'tcp://10.7.0.133:46241']
dask.array<concatenate, shape=(12, 16384, 16384), dtype=float64, chunksize=(1, 8192, 8192), chunktype=numpy.ndarray>
Generated contract {'global_t': [(0, 12, 1)]}
Contract has been signed
Original arrays deleted
EST_ANALYTICS_TIME:  101.13077
Done
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: 'tcp://10.7.0.129:8786' processes=60 threads=2400, memory=9.38 TiB>>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/client.py", line 1099, in _heartbeat
    self.scheduler_comm.send({"op": "heartbeat-client"})
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Client->Scheduler local=tcp://10.7.0.129:34974 remote=tcp://10.7.0.129:8786> already closed.

functions called:
SIMULATION_TIME:     107.146372426999974 (avg: 8.928864368916665)
PDI_DELAY:           23.093828313999978 (avg: 1.924485692833332)
SIM_WTHOUT_PDI:      84.052544112999996 (avg: 7.004378676083333)
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://10.7.0.136:58382 remote=tcp://10.7.0.129:8786>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://10.7.0.135:39632 remote=tcp://10.7.0.129:8786>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
SUCCESS
HTML_ANALYTICS_TIME:      99.54
HTML_TRANSFER_TIME:       102.75
HTML_DESERIALIZE_TIME:    17.11
HTML_COMPUTE_TIME:        37.47
